title: Fat Pandas
author: Paige Bolduc
email: pbold1@ocdsb.ca
description: > Welcome to the land of fat pandas.
# social links
twitter_username: none
github_username:  paigebolduc

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
